DROP TABLE IF EXISTS athz_permission;
DROP TABLE IF EXISTS usr_user;
DROP TABLE IF EXISTS act_account;

CREATE TABLE athz_permission (
  scope_id             	    BIGINT(21) 	  UNSIGNED NOT NULL,
  id                     	BIGINT(21) 	  UNSIGNED NOT NULL,
  created_on             	TIMESTAMP(3)  DEFAULT 0,
  created_by             	BIGINT(21)    UNSIGNED NOT NULL,
  
  user_id					BIGINT(21) 	  UNSIGNED NOT NULL,
  domain					VARCHAR(64)   NOT NULL,
  action					VARCHAR(64),
  target_scope_id		    BIGINT(21),
  
  PRIMARY KEY (id),
  
  UNIQUE INDEX idx_permissionScopeId (scope_id, user_id, domain, action, target_scope_id)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE act_account (
  scope_id          		 BIGINT(21) 	  UNSIGNED,
  id                         BIGINT(21) 	  UNSIGNED NOT NULL,
  name                       VARCHAR(255) 	  NOT NULL,
  created_on                 TIMESTAMP 		  DEFAULT 0,
  created_by                 BIGINT(21) 	  UNSIGNED NOT NULL,
  modified_on                TIMESTAMP 		  NOT NULL,
  modified_by                BIGINT(21) 	  UNSIGNED NOT NULL,
  org_name                   VARCHAR(255) 	  NOT NULL,
  org_person_name            VARCHAR(255) 	  DEFAULT "",
  org_email                  VARCHAR(255) 	  NOT NULL,
  org_phone_number           VARCHAR(64),
  org_address_line_1         VARCHAR(255),
  org_address_line_2         VARCHAR(255),
  org_address_line_3         VARCHAR(255),
  org_zip_postcode           VARCHAR(255),
  org_city                   VARCHAR(255),
  org_state_province_county  VARCHAR(255),
  org_country                VARCHAR(255),
  parent_account_path        VARCHAR(64),
  optlock                    INT UNSIGNED,
  attributes				 TEXT,
  properties                 TEXT,
  PRIMARY KEY  (id),
  FOREIGN KEY (scope_id) REFERENCES act_account(id) ON DELETE RESTRICT,
  CONSTRAINT act_accountName UNIQUE (name),
  INDEX idx_accountScopeId (scope_id)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `edcdb`.`act_account` ( 
	`scope_id`,
	`id`,
	`name`,
	`created_on`,
	`created_by`,
	`modified_on`,
	`modified_by`,
	`org_name`,
	`org_person_name`,
	`org_email`,
	`org_phone_number`,
	`org_address_line_1`,
	`org_address_line_2`,
	`org_address_line_3`,
	`org_zip_postcode`,
	`org_city`,
	`org_state_province_county`,
	`org_country`,
	`parent_account_path`,
	`optlock`,
	`attributes`,
	`properties`) 
VALUES (NULL,
		1,
		'kapua-sys',
		'0000-00-00 00:00:00',
		1,
		'0000-00-00 00:00:00',
		1,
		'kapua-org',
		'Kapua Sysadmin',
		'kapua-sys@eclipse.org',
		'+1 555 123 4567',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
        NULL,
		'\1',
		0,
		NULL,
		NULL);

CREATE TABLE edcdb.usr_user (
  scope_id             		BIGINT(21) 	  UNSIGNED NOT NULL,
  id                     	BIGINT(21) 	  UNSIGNED NOT NULL,
  name               	    VARCHAR(255)  NOT NULL,
  created_on             	TIMESTAMP(3)  NOT NULL,
  created_by             	BIGINT(21)    UNSIGNED NOT NULL,
  modified_on            	TIMESTAMP(3),
  modified_by            	BIGINT(21)    UNSIGNED,
  status                 	VARCHAR(64)   NOT NULL DEFAULT 'ENABLED',
  display_name           	VARCHAR(255),
  email                  	VARCHAR(255),
  phone_number           	VARCHAR(64),
  password               	VARCHAR(255)  NOT NULL,
  salt                   	VARCHAR(64),
  optlock               	INT UNSIGNED,
  attributes             	TEXT,  
  properties             	TEXT,  
  PRIMARY KEY (id),
  CONSTRAINT usr_uc_name UNIQUE (name),
  INDEX idx_userScopeId (scope_id)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `usr_user` (`scope_id`,
						`id`,
						`name`,
						`created_on`,
						`created_by`,
						`modified_on`,
						`modified_by`,
						`status`,
						`display_name`,
						`email`,
						`phone_number`,
						`password`,
						`salt`,
						`optlock`,
						`attributes`,
						`properties`) 
		VALUES (1,
				1,
				'kapua-sys',
				'0000-00-00 00:00:00',
				1,
				'0000-00-00 00:00:00',
				1,
				'ENABLED',
				'Kapua Sysadmin',
				'kapua-sys@eclipse.org',
				'+1 555 123 4567',
				'We!come12345',
				NULL,
				0,
				NULL,
				NULL);
		
INSERT INTO `athz_permission` (`scope_id`, 
								`id`,
								`created_on`,
								`created_by`,
								`user_id`,
								`domain`,
								`action`,
								`target_scope_id`) 
		VALUES ('1', 
				'1',
				'0000-00-00 00:00:00',
				'1',
				'1', 
				'account',
				NULL,
				NULL);

INSERT INTO `athz_permission` (`scope_id`, 
								`id`,
								`created_on`,
								`created_by`,
								`user_id`,
								`domain`,
								`action`,
								`target_scope_id`) 
		VALUES ('1', 
				'2',
				'0000-00-00 00:00:00',
				'1',
				'1', 
				'user',
				NULL,
				NULL);