package org.eclipse.kapua.app.console.shared;

public enum GwtEdcErrorCode {
    CANNOT_REMOVE_LAST_ADMIN,
    CURRENT_ADMIN_PASSWORD_DOES_NOT_MATCH,
    DUPLICATE_NAME,
    ILLEGAL_ACCESS,
    ILLEGAL_ARGUMENT,
    ILLEGAL_NULL_ARGUMENT,
    INTERNAL_ERROR,
    INVALID_RULE_QUERY,
    INVALID_USERNAME_PASSWORD,
    INVALID_XSRF_TOKEN,
    LOCKED_USER,
    OVER_RULE_LIMIT,
    UNAUTHENTICATED,
    WARNING,
    XSRF_INVALID_TOKEN;
}