INSERT INTO `athz_permission` (`scope_id`, `id`, `created_on`, `created_by`, `user_id`, `domain`, `action`, `target_scope_id`) 
		VALUES ('1', '1',  CURRENT_TIMESTAMP(), '1', '1', 'account', NULL, NULL),
			   ('1', '2',  CURRENT_TIMESTAMP(), '1', '1', 'user', NULL, NULL),
			   ('1', '3',  CURRENT_TIMESTAMP(), '1', '1', 'device-event', NULL, NULL),
			   ('1', '4',  CURRENT_TIMESTAMP(), '1', '1', 'device-connection', NULL, NULL),
			   ('1', '5',  CURRENT_TIMESTAMP(), '1', '1', 'device', NULL, NULL),
			   ('1', '6',  CURRENT_TIMESTAMP(), '1', '1', 'data', NULL, NULL),
			   ('1', '7',  CURRENT_TIMESTAMP(), '1', '1', 'broker', NULL, NULL),
			   ('1', '8',  CURRENT_TIMESTAMP(), '1', '2', 'account', NULL, NULL),
			   ('1', '9',  CURRENT_TIMESTAMP(), '1', '2', 'user', NULL, NULL),
			   ('1', '11', CURRENT_TIMESTAMP(), '1', '2', 'device-event', NULL, NULL),
			   ('1', '12', CURRENT_TIMESTAMP(), '1', '2', 'device-connection', NULL, NULL),
			   ('1', '13', CURRENT_TIMESTAMP(), '1', '2', 'device', NULL, NULL),
			   ('1', '14', CURRENT_TIMESTAMP(), '1', '2', 'data', NULL, NULL),
			   ('1', '15', CURRENT_TIMESTAMP(), '1', '2', 'broker', NULL, NULL);
