INSERT INTO `athz_permission` (`scope_id`, `id`, `created_on`, `created_by`, `user_id`, `domain`, `action`, `target_scope_id`) 
		VALUES ('1', '1',  UTC_TIMESTAMP(), '1', '1', 'account', NULL, NULL),
			   ('1', '2',  UTC_TIMESTAMP(), '1', '1', 'user', NULL, NULL),
			   ('1', '3',  UTC_TIMESTAMP(), '1', '1', 'device-event', NULL, NULL),
			   ('1', '4',  UTC_TIMESTAMP(), '1', '1', 'device-connection', NULL, NULL),
			   ('1', '5',  UTC_TIMESTAMP(), '1', '1', 'device', NULL, NULL),
			   ('1', '6',  UTC_TIMESTAMP(), '1', '1', 'data', NULL, NULL),
			   ('1', '7',  UTC_TIMESTAMP(), '1', '1', 'broker', NULL, NULL),
			   ('1', '8',  UTC_TIMESTAMP(), '1', '2', 'account', NULL, NULL),
			   ('1', '9',  UTC_TIMESTAMP(), '1', '2', 'user', NULL, NULL),
			   ('1', '11', UTC_TIMESTAMP(), '1', '2', 'device-event', NULL, NULL),
			   ('1', '12', UTC_TIMESTAMP(), '1', '2', 'device-connection', NULL, NULL),
			   ('1', '13', UTC_TIMESTAMP(), '1', '2', 'device', NULL, NULL),
			   ('1', '14', UTC_TIMESTAMP(), '1', '2', 'data', NULL, NULL),
			   ('1', '15', UTC_TIMESTAMP(), '1', '2', 'broker', NULL, NULL);
